language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t khkz211/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true khkz211/docker-react npm run test 
